# pull official base image
FROM python:3.8.9

# set work directory
WORKDIR /usr/src/coin_bot

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV FLASK_APP=app/app.py
# watch app' files
ENV FLASK_DEBUG=true
ENV FLASK_ENV=development

# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/coin_bot/requirements.txt
RUN pip install -r requirements.txt

# copy project
COPY . /usr/src/coin_bot/

ENTRYPOINT ["/usr/src/coin_bot/entrypoint.sh"]

